version: "3.9"

services:
  stateless-auth-db:
    container_name: stateless-auth-db
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - "./.docker/stateless-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=auth-stateful
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=auth-db

  stateful-auth-db:
    container_name: stateful-auth-db
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - "./.docker/stateful-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=auth-stateful
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=auth-db

  token-redis:
    container_name: token-redis
    image: redis:latest
    ports:
      - "6379:6379"