version: "3.9"

services:
  stateful-auth-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - "./.docker/pg-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=auth-stateful
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=auth-db

  token-redis:
    image: redis:latest
    ports:
      - "6379:6379"